CREATE TABLE IF NOT EXISTS domain.coins (
    name VARCHAR(255) PRIMARY KEY NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    min_price DOUBLE PRECISION NOT NULL,
    max_price DOUBLE PRECISION NOT NULL,
    hour_change_price DOUBLE PRECISION NOT NULL
);