---
openapi: 3.0.3
info:
  title: CryptoRatesAPI
  description: Crypto API for retrieving and managing cryptocurrency rates
  contact:
    email: skantay03.business@gmail.com
  version: 1.0.0
servers:
- url: /
paths:
  /rates:
    get:
      tags:
      - rates
      summary: Get cryptocurrency information
      description: |
        Get information about a specific cryptocurrency, including its minimum and maximum prices, and hourly change.
      operationId: getCryptoInfo
      parameters:
      - name: cryptocurrency
        in: query
        description: "The cryptocurrency code (e.g., BTC, ETH)"
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/coinItem'
        "404":
          description: Cryptocurrency not found
  /telegram/start:
    post:
      tags:
      - telegram
      summary: Start the Telegram bot
      description: Start the Telegram bot and subscribe to updates.
      operationId: startTelegramBot
      responses:
        "200":
          description: Successful response
        "405":
          description: Method not allowed
  /telegram/auto-update:
    post:
      tags:
      - telegram
      summary: Set automatic updates for the Telegram bot
      description: Set the interval for automatic updates from the Telegram bot.
      operationId: setAutoUpdate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/telegram_autoupdate_body'
        required: true
      responses:
        "200":
          description: Successful response
        "405":
          description: Method not allowed
components:
  schemas:
    coinItem:
      required:
      - hour_change_price
      - max_price
      - min_price
      - name
      type: object
      properties:
        name:
          type: string
          example: BTC
        price:
          type: int
          example: 500
        min_price:
          type: integer
          example: 100
        max_price:
          type: integer
          example: 1000
        hour_change_price:
          type: number
          example: 1.5
    telegram_autoupdate_body:
      type: object
      properties:
        minutes_count:
          type: integer
